### ISSUE TITLE
Latest release breaks ember-cli builds

### ISSUE THREAD

**Issue by raytiley** [rwjblue/ember-cli-ic-ajax#10]
![windows 7 x64 2015-06-26 10-33-52](https://cloud.githubusercontent.com/assets/41680/8379562/d96ba06a-1bee-11e5-8166-912d85434ad2.png)

**Comment by rwjblue** [comment]
Thanks for reporting! @stefanpenner seems related to #9

**Comment by ryanhollister** [comment]
Seeing this on mac as well.

**Comment by rwjblue** [comment]
Pinning apps to 0.1.2 should fix the build failure in the app, I'll review and get on this today though.

**Comment by stefanpenner** [comment]
> Pinning apps to 0.1.2 should fix the build failure in the app, I'll review and get on this today though.

that release should have been 0.2 or 1.0.x, yank and re-publish semver compliant

**Comment by stefanpenner** [comment]
Let me know when it has been republished so i can update the ember-cli PR and land the update to support npmv3

**Comment by stefanpenner** [comment]
Actually, this shouldn't be happening, since ember-cli locks to a specific version https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/package.json#L29

We should still be sure the release version correct indicates intent, as users upgrading/downgrading manually will potentially end up with a more liberal semver constraint.

**Comment by rwjblue** [comment]
> that release should have been 0.2 or 1.0.x, yank and re-publish to be better aligned with semver.

We didn't change the intent, the change should have been a no-op for npm 2.x but wasn't.  This is a bug, not a SemVer breakage issue.

**Comment by stefanpenner** [comment]
> We didn't change the intent, the change should have been a no-op for npm 2.x but wasn't. This is a bug, not a SemVer breakage issue.

not that isn't true, it was expected to break with ember-cli's companion patch.

**Comment by stefanpenner** [comment]
ember-cli incorrect does a `path.join` rather then `path.resolve`

**Comment by rwjblue** [comment]
Reverted changes in #9 and released 0.1.4.

**Comment by rwjblue** [comment]
re-released the changes in #9 as 0.2.0.
