### ISSUE TITLE
Path or pattern "vendor/ic-ajax/dist/named-amd/main.js" did not match any files

### ISSUE THREAD

**Issue by jcope2013** [rwjblue/ember-cli-ic-ajax#11]
updated to 0.2.0, was previously working fine on 0.1.2, any other steps to take?

**Comment by rwjblue** [comment]
@jcope2013 0.2.0 is only valid with a future version of ember-cli, you should use 0.1.4

**Comment by arinhouck** [comment]
I'm having the same issue even after changing to 0.1.4. Everything runs fine locally, but my heroku build is still crashing for the same error. I am using `npm 2.12.1` locally and specified in my engines hash the same version, but it appears heroku uses `Using default npm version: 3.3.6` by default.

**Comment by rwjblue** [comment]
Latest is 0.2.4, and should be compatible with npm 3 layouts.

**Comment by arinhouck** [comment]
I changed to ember-ajax and it fixed my problem!
